---
name: Amazon ECS "PRE-Render Task Definition Secrets" Action for GitHub Actions
description: Renders Parameter Store Secrets into ECS Task Definition.
branding:
  icon: cloud
  color: orange
inputs:
  task_definition:
    description: 'The path to the ECS task definition JSON file'
    required: true
  envs:
    description: 'The list of variables the application will launch with'
    required: true
  paths:
    description: 'Paths for parameter store variables'
    required: true
  region:
    description: 'AWS region for parameter store'
    required: true
outputs:
  task-definition:
    description: 'Output with rendered task definition file'
runs:
  using: node20
  main: dist/index.js
